[package]
name = "rust-core"
version = "0.1.0"
edition = "2024"

[lib]
name = "rust_core"
crate-type = ["cdylib","rlib"]   # cdylib for shared lib

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
