services:
  backend:
    image: ghcr.io/diegobraga92/opentodo-backend:latest
    container_name: opentodo-backend
    ports:
      - "3000:3000"
    volumes:
      - backend_data:/app
    restart: unless-stopped

  web:
    image: ghcr.io/diegobraga92/opentodo-web:latest
    container_name: opentodo-web
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data: